'use strict';

/* ═══════════════════════════════════════════════════════════════════
   AL FAROOQUE Manufacturing — Unified Submission Handler
   Vercel Serverless Function  (POST /api/quote)

   Handles ALL website form submissions and emails them to the sales
   inbox via the Resend API (https://resend.com):

     • type: "contact"  →  Request-a-Quote / Contact form
     • type: "order"    →  Direct "Order Now" (single product)
     • type: "cart"     →  Cart "Proceed to Order" (multiple products)

   Required env vars:
     RESEND_API_KEY   — your Resend API key (required to send)
     RESEND_FROM      — verified sender address
                        (use onboarding@resend.dev for local testing)

   Set them in:
     • Local:      .env.local  (loaded automatically by server.js)
     • Production: Vercel Dashboard → Project → Settings → Environment Variables
   ═══════════════════════════════════════════════════════════════════ */

const crypto = require('crypto');
const mailer = require('./_email');

const FROM_NAME = 'AL FAROOQUE Website';

/* ── Additive, non-blocking DB persistence ──────────────────────────
   Gives the admin dashboard a live record of every submission (quote
   requests + guest orders), in addition to the existing email — the
   email send is the critical path and is never affected by this. If
   SUPABASE_SERVICE_ROLE_KEY isn't configured yet, this silently no-ops.

   `recordId` is generated by the caller BEFORE the email is sent so the
   same id can be embedded in the email's "View Order" button — the row
   is inserted with that exact id (overriding the column's random default)
   so the link and the database record always agree. */
/* Resolve the real signed-in customer server-side from their Supabase
   access token (Authorization: Bearer <jwt>) — never trust a client-
   supplied user id. Returns null for guests or an invalid/expired token
   (the order is then saved as a guest order, same as before). */
async function resolveUserId(req, sb) {
  const header = req.headers.authorization || '';
  const token = header.startsWith('Bearer ') ? header.slice(7).trim() : null;
  if (!token) return null;
  try {
    const { data, error } = await sb.auth.getUser(token);
    if (error || !data || !data.user) return null;
    return data.user.id;
  } catch (_) { return null; }
}

/* This is the ONLY place an order (or quote) row is ever inserted — both
   the Direct Order and Cart Checkout flows funnel through this exact
   function with exactly one call each, for both guest and signed-in
   customers. There is no separate client-side insert anymore, which is
   what previously caused a second (and, for cart orders, incomplete)
   order row per checkout.

   `recordId` doubles as an idempotency key: it's the client's stable
   per-checkout-attempt id (see buildPayload()'s clientOrderId), so a
   retried/duplicated request (double click, page refresh mid-request,
   network retry) upserts the SAME row instead of inserting a second one
   — `ignoreDuplicates` makes this an atomic, single-statement no-op on
   a repeat, never a partial or duplicate write. */
async function persistSubmission(type, d, recordId, userId) {
  let getAdminClient;
  try { ({ getAdminClient } = require('./_supabaseAdmin')); } catch (_) { return; }
  let sb;
  try { sb = getAdminClient(); } catch (_) { return; } // not configured — skip quietly

  if (type === 'contact') {
    await sb.from('quotes').upsert({
      id: recordId,
      name: d.fullName || null, email: d.email || null, phone: d.phone || null,
      message: d.message || null, product: d.service || null, status: 'new',
    }, { onConflict: 'id', ignoreDuplicates: true });
    return;
  }

  /* order / cart → same schema/table either way; guest when not signed in
     (user_id null, visible only to admin via service role), linked to the
     real account when signed in. Never insert with zero items — an
     order record with nothing purchased is worse than no record. */
  const items = d.items && d.items.length
    ? d.items.map(it => ({ name: it.name, qty: it.qty, price: it.price != null ? it.price : (it.lineTotal && it.qty ? it.lineTotal / it.qty : 0) }))
    : (d.product ? [{ name: d.product, qty: d.quantity || 1, price: d.quantity ? (Number(d.subtotal) || 0) / d.quantity : (Number(d.subtotal) || 0) }] : []);

  if (!items.length) {
    console.error('[Submit] Refusing to persist an order with 0 items.', { type, fullName: d.fullName, email: d.email });
    return;
  }

  const { error } = await sb.from('orders').upsert({
    id: recordId,
    user_id: userId || null,
    order_no: 'ORD-' + Date.now().toString(36).toUpperCase(),
    status: 'pending',
    source: userId ? 'account' : 'guest',
    guest_name: d.fullName || null,
    guest_email: d.email || null,
    guest_phone: d.phone || null,
    items,
    subtotal: Number(d.subtotal) || 0,
    vat: Number(d.vat) || 0,
    grand_total: Number(d.grandTotal) || 0,
  }, { onConflict: 'id', ignoreDuplicates: true });
  if (error) console.error('[Submit] Order persist failed:', error.message, '| type:', type, '| items:', items.length);
}

/* ── Absolute site origin, for the "View Order" email button ── */
function siteOrigin(req) {
  const proto = (req.headers['x-forwarded-proto'] || 'https').split(',')[0].trim();
  const host = req.headers['x-forwarded-host'] || req.headers.host || 'alfarooque.com';
  return proto + '://' + host;
}

module.exports = async function handler(req, res) {
  console.log('[Submit] Incoming —', req.method, req.url);

  /* ── CORS ── */
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();

  if (req.method !== 'POST') {
    console.warn('[Submit] Rejected non-POST method:', req.method);
    return res.status(405).json({ error: 'Method not allowed' });
  }

  /* ── Email configuration check (Resend or SMTP) ── */
  const cfg = mailer.getStatus();
  if (!cfg.configured) {
    console.error('[Submit] Email service NOT configured —', cfg.reason);
    return res.status(500).json({
      error:   'Email service is not configured on the server.',
      code:    'NO_CONFIG',
      missing: cfg.missing,
    });
  }
  const RECIPIENT = cfg.to;

  /* ── Parse body (Vercel auto-parses JSON; guard for raw stream too) ── */
  let body = req.body;
  if (!body || typeof body !== 'object') {
    try {
      const raw = await new Promise((resolve, reject) => {
        let s = '';
        req.on('data', c => (s += c));
        req.on('end', () => resolve(s));
        req.on('error', reject);
      });
      body = JSON.parse(raw || '{}');
    } catch (err) {
      console.error('[Submit] Body parse error:', err.message);
      return res.status(400).json({ error: 'Invalid request body (expected JSON)' });
    }
  }

  /* ── Normalise common fields ── */
  const type     = (body.type || 'contact').toLowerCase();
  const language = body.language === 'ar' ? 'ar' : 'en';

  const fullName = (
    body.name ||
    (body.first_name ? `${body.first_name} ${body.last_name || ''}` : '')
  ).trim();

  const email   = (body.email   || '').trim();
  const phone   = (body.phone   || '').trim();
  const company = (body.company || '').trim();
  const message = (body.message || '').trim();

  /* Request metadata */
  const userAgent = req.headers['user-agent'] || '(unknown)';
  const ip =
    (req.headers['x-forwarded-for'] || '').split(',')[0].trim() ||
    (req.socket && req.socket.remoteAddress) ||
    '(unknown)';

  /* ── Validation (real, per type) ── */
  const errors = [];
  if (type === 'contact') {
    if (!fullName) errors.push('Name is required');
    if (!email)    errors.push('Email is required');
  } else {
    /* order / cart */
    if (!fullName) errors.push('Name is required');
    if (!phone)    errors.push('Phone is required');
  }
  if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    errors.push('Email address is invalid');
  }
  if (errors.length) {
    console.warn('[Submit] Validation failed:', errors, '| type:', type);
    return res.status(400).json({ error: errors.join('. '), fields: errors });
  }

  /* ── Build subject + email ── */
  const labels = {
    contact: 'New Quote Request',
    order:   'New Product Order',
    cart:    'New Cart Order',
  };
  const label   = labels[type] || labels.contact;
  const subjBit = type === 'contact'
    ? (body.service || 'General Enquiry')
    : (body.product || (Array.isArray(body.items) ? `${body.items.length} item(s)` : 'Order'));
  const subject = `${label} — ${subjBit} — ${fullName || email || phone}`;

  /* Idempotency: the client generates ONE id per checkout attempt (see
     buildPayload()'s clientOrderId) and resends the SAME one on any retry
     of that same attempt (double click, page refresh mid-request, network
     retry) — persistSubmission's upsert(on conflict id, ignoreDuplicates)
     then guarantees exactly one row no matter how many times this handler
     runs for that attempt. Falls back to a fresh id for older clients or
     non-order submission types, which don't carry a clientOrderId. This id
     is also embedded in the email's "View Order" button either way. */
  const isValidUuid = typeof body.clientOrderId === 'string' && /^[0-9a-f-]{16,36}$/i.test(body.clientOrderId);
  const recordId = isValidUuid ? body.clientOrderId : crypto.randomUUID();
  const viewParam = type === 'contact' ? 'openQuote' : 'openOrder';
  const viewUrl = siteOrigin(req) + '/admin?' + viewParam + '=' + recordId;

  const htmlBody = buildEmailHTML({
    type, label, language, fullName, company, email, phone, message,
    service:    body.service,
    product:    body.product,
    quantity:   body.quantity,
    items:      Array.isArray(body.items) ? body.items : null,
    subtotal:   body.subtotal,
    vat:        body.vat,
    grandTotal: body.grandTotal,
    userAgent, ip, viewUrl,
  });

  console.log('[Submit] →', RECIPIENT, '| via:', cfg.provider, '| type:', type, '| subject:', subject, '| ip:', ip);

  /* ── Send via the configured provider (Resend or SMTP) ── */
  try {
    const result = await mailer.sendEmail({
      from:    cfg.from ? `${FROM_NAME} <${cfg.from}>` : undefined,
      to:      RECIPIENT,
      replyTo: email || undefined,
      subject,
      html:    htmlBody,
    });
    console.log('[Submit] SUCCESS — id:', result.id, '| provider:', result.provider, '→', RECIPIENT);
    try {
      let userId = null;
      try {
        const { getAdminClient } = require('./_supabaseAdmin');
        userId = await resolveUserId(req, getAdminClient());
      } catch (_) { /* auth not configured — treat as guest */ }
      await persistSubmission(type, {
        fullName, email, phone, company, message, service: body.service,
        items: Array.isArray(body.items) ? body.items : null,
        product: body.product, quantity: body.quantity,
        subtotal: body.subtotal, vat: body.vat, grandTotal: body.grandTotal,
      }, recordId, userId);
    } catch (dbErr) {
      console.error('[Submit] DB persist failed (non-fatal, email already sent):', dbErr.message);
    }
    return res.status(200).json({ success: true, id: result.id, provider: result.provider });
  } catch (err) {
    console.error('[Submit] Email delivery FAILED —', err.code || 'ERROR', ':', err.message, err.detail || '');
    const httpStatus = err.code === 'NO_CONFIG' ? 500 : 502;
    return res.status(httpStatus).json({
      error:  err.message || 'Email delivery failed',
      code:   err.code || 'SEND_FAILED',
      detail: err.detail,
    });
  }
};

/* ── HTML escape ── */
function esc(str) {
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\n/g, '<br>');
}

/* ── Currency ── */
function money(n) {
  if (n == null || n === '') return '—';
  const num = Number(n);
  if (Number.isNaN(num)) return esc(n);
  return 'SAR ' + num.toLocaleString('en-US');
}

/* ── Email template (covers contact + order + cart) ── */
function buildEmailHTML(d) {
  const ts = new Date().toLocaleString('en-SA', {
    timeZone: 'Asia/Riyadh', dateStyle: 'long', timeStyle: 'short',
  });
  const langName = d.language === 'ar' ? 'Arabic (العربية)' : 'English';

  function row(lbl, val) {
    return `<tr><td class="lbl">${esc(lbl)}</td><td class="val">${val}</td></tr>`;
  }

  /* Contact details rows */
  const detailRows = [
    row('Name', esc(d.fullName || '—')),
    d.company ? row('Company', esc(d.company)) : '',
    row('Email', d.email ? `<a href="mailto:${esc(d.email)}" style="color:#0ea5e9;">${esc(d.email)}</a>` : '—'),
    row('Phone / WhatsApp', esc(d.phone || '—')),
    d.service ? row('Service Required', esc(d.service)) : '',
  ].join('');

  /* Order rows */
  let orderBlock = '';
  if (d.type === 'order' || d.type === 'cart') {
    let itemsHtml = '';
    if (d.items && d.items.length) {
      itemsHtml = d.items.map(it =>
        `<tr>
           <td class="it-name">${esc(it.name)}</td>
           <td class="it-qty">×&nbsp;${esc(it.qty)}</td>
           <td class="it-tot">${money(it.lineTotal != null ? it.lineTotal : (Number(it.price) * Number(it.qty)))}</td>
         </tr>`
      ).join('');
    } else if (d.product) {
      itemsHtml =
        `<tr>
           <td class="it-name">${esc(d.product)}</td>
           <td class="it-qty">×&nbsp;${esc(d.quantity || 1)}</td>
           <td class="it-tot">${money(d.subtotal)}</td>
         </tr>`;
    }

    orderBlock = `
      <div class="sec-lbl">Order Details</div>
      <table class="items">${itemsHtml}</table>
      <table class="totals">
        ${row('Subtotal', money(d.subtotal))}
        ${row('VAT (15%)', money(d.vat))}
        <tr class="grand"><td class="lbl">Grand Total</td><td class="val">${money(d.grandTotal)}</td></tr>
      </table>`;
  }

  const msgBlock = d.message
    ? `<div class="sec-lbl">${d.type === 'contact' ? 'Project Description' : 'Customer Message'}</div>
       <div class="msg-box">${esc(d.message)}</div>`
    : '';

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<style>
  body{margin:0;padding:0;background:#f4f4f4;font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;}
  .wrap{max-width:620px;margin:32px auto;background:#fff;border-radius:10px;overflow:hidden;border:1px solid #e0e0e0;}
  .hdr{background:linear-gradient(135deg,#0f2442 0%,#1a3a6b 100%);padding:28px 32px;color:#fff;}
  .hdr-title{font-size:21px;font-weight:700;margin:0 0 6px;}
  .hdr-sub{font-size:12px;opacity:0.7;margin:0;}
  .body{padding:24px 32px;}
  .sec-lbl{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.6px;color:#7a8aa0;margin:22px 0 10px;}
  table{width:100%;border-collapse:collapse;}
  .lbl{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;color:#888;padding:9px 0;width:150px;vertical-align:top;}
  .val{font-size:14px;color:#1a1a1a;line-height:1.5;padding:9px 0;border-bottom:1px solid #f1f1f1;}
  .items td{font-size:14px;padding:8px 0;border-bottom:1px solid #f1f1f1;}
  .it-name{color:#1a1a1a;}
  .it-qty{color:#666;text-align:center;width:70px;white-space:nowrap;}
  .it-tot{color:#1a1a1a;font-weight:600;text-align:right;width:120px;white-space:nowrap;}
  .totals{margin-top:6px;}
  .totals .lbl{padding:6px 0;border:none;}
  .totals .val{text-align:right;border:none;padding:6px 0;}
  .totals .grand .lbl,.totals .grand .val{font-size:16px;font-weight:700;color:#0f2442;border-top:2px solid #0f2442;padding-top:10px;}
  .msg-box{background:#f7fbfd;border-left:3px solid #22c4de;border-radius:0 6px 6px 0;padding:14px 16px;font-size:14px;line-height:1.7;color:#333;}
  .meta{margin-top:24px;padding-top:14px;border-top:1px solid #eee;font-size:11px;color:#aaa;line-height:1.7;}
  .ftr{background:#f9f9f9;padding:14px 32px;font-size:11px;color:#999;border-top:1px solid #eee;text-align:center;}
  .cta-row{text-align:center;margin:6px 0 4px;}
  .cta-btn{display:inline-block;background:#0891a8;color:#ffffff !important;text-decoration:none;font-weight:700;font-size:14px;padding:13px 30px;border-radius:8px;}
</style></head>
<body>
<div class="wrap">
  <div class="hdr">
    <div class="hdr-title">${esc(d.label)}</div>
    <div class="hdr-sub">AL FAROOQUE Manufacturing &mdash; ${esc(ts)} (AST)</div>
  </div>
  <div class="body">
    ${d.viewUrl ? `<div class="cta-row"><a class="cta-btn" href="${esc(d.viewUrl)}" target="_blank" rel="noopener">View Order</a></div>` : ''}
    <div class="sec-lbl">Customer</div>
    <table>${detailRows}</table>
    ${orderBlock}
    ${msgBlock}
    <div class="meta">
      Company: AL FAROOQUE Manufacturing &bull; Language: ${esc(langName)}<br>
      Browser: ${esc(d.userAgent)}<br>
      IP: ${esc(d.ip)}
    </div>
  </div>
  <div class="ftr">Submitted via alfarooque.com &mdash; reply directly to respond to the customer.</div>
</div>
</body></html>`;
}
